<?php

namespace Meesters\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrderedByPosition()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                    ->select('c, f, p')
                    ->from('MeestersForumBundle:Category', 'c')
                    ->join('c.forums', 'f')
                    ->leftJoin('f.last_post', 'p')
                    ->orderBy('c.position', 'ASC')
                    ->orderBy('f.position', 'ASC')
                    ->getQuery();
        
        return $query->getResult();
    }
    
    public function findOneByIdOrderedByPosition($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                    ->select('c, f, p')
                    ->from('MeestersForumBundle:Category', 'c')
                    ->join('c.forums', 'f')
                    ->leftJoin('f.last_post', 'p')
                    ->where('c.id = :id')
                    ->orderBy('c.position', 'ASC')
                    ->orderBy('f.position', 'ASC')
                    ->setParameter('id', $id)
                    ->getQuery();
        
        return $query->getSingleResult();
    }

}