Meesters\UserBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: Meesters\UserBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        topics:
            targetEntity: Meesters\ForumBundle\Entity\Topic
            mappedBy: user
        posts:
            targetEntity: Meesters\ForumBundle\Entity\Post
            mappedBy: user
    lifecycleCallbacks: {  }