parameters:
#    meesters_user.example.class: Meesters\UserBundle\Example

services:
#    meesters_user.example:
#        class: %meesters_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
