Meesters\ForumBundle\Entity\Forum:
    type: entity
    table: forums
    repositoryClass: Meesters\ForumBundle\Entity\ForumRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '100'
        description:
            type: text
        position:
            type: smallint
    manyToOne:
        category:
            targetEntity: Meesters\ForumBundle\Entity\Category
            inversedBy: forums
            cascade: [persist, remove]
    oneToMany:
        topics:
            targetEntity: Meesters\ForumBundle\Entity\Topic
            mappedBy: forum
            cascade: [persist]
            orderBy:
                sticky: DESC
                time: DESC
    lifecycleCallbacks: {  }