Meesters\ForumBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: Meesters\ForumBundle\Entity\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        message:
            type: text
        time:
            type: datetime
        edit_count:
            type: integer
        edit_time:
            type: datetime
            nullable: true
    manyToOne:
        topic:
            targetEntity: Meesters\ForumBundle\Entity\Topic
            inversedBy: posts
        user:
            targetEntity: Meesters\UserBundle\Entity\User
            inversedBy: posts
        edit_user:
            targetEntity: Meesters\UserBundle\Entity\User
            nullable: true
    lifecycleCallbacks:
        prePersist: [ create ]
        preUpdate:  [ update ]
